import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Advice from './advice'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Advice & Weather-Info</title>
        <meta name="description" content="Generated by Muhammad Nasir" />
        <link rel="icon" href="/LN1.png" />
      </Head>
      <Advice />
    </div>
  )
}
