import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Advice from './advice'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Advice Api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello Nasir welcome</h1>
      <p>after editing what will be do.</p>
      <Advice />
    </div>
  )
}
